import {
  Scene,
  BrandKit,
  AuthoritativeTimerState,
  AnnouncementItem,
  ScheduleItem,
  AssetItem,
  EventState,
} from '@/types/smartscreen';

export const defaultBrandKit: BrandKit = {
  eventName: 'GLOBAL TECH SUMMIT 2026',
  tagline: 'Leading the Future of Autonomous Systems & AI',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80',
  primaryColor: '#3b82f6',
  secondaryColor: '#60a5fa',
  accentColor: '#3b82f6',
  backgroundColor: '#000000',
  fontFamily: 'Inter, system-ui, sans-serif',
  sponsorLogos: [],
};

export const defaultTimerState: AuthoritativeTimerState = {
  status: 'stopped',
  mode: 'countdown',
  targetEndTime: null,
  pausedRemaining: 15 * 60 * 1000, // 15 mins
  totalDuration: 15 * 60 * 1000,
  startTime: null,
  label: 'ROUND 1 COUNTDOWN',
  subtitle: 'Keep all work strictly concealed until time expires',
  updatedAt: Date.now(),
  style: 'massive',
  showHours: false,
  showSeconds: true,
  showMilliseconds: false,
  showProgressBar: true,
  soundOnFinish: true,
  finishMessage: "TIME EXPIRED • PENCILS DOWN",
  warningThresholdSeconds: 120,
  criticalThresholdSeconds: 30,
  allowNegativeOvertime: false,
  blinkSeparator: true,
  fontFamily: 'mono',
};

export const defaultScenes: Scene[] = [
  {
    id: 'scene-welcome',
    name: 'Main Welcome Display',
    type: 'welcome',
    description: 'Hero presentation for conference arrival and main hall',
    background: {
      type: 'gradient',
      value: 'radial-gradient(ellipse at top, #1e1b4b 0%, #090d16 65%, #030712 100%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 3600000,
    elements: [
      {
        id: 'el-welcome-badge',
        type: 'text',
        name: 'Event Pill Badge',
        style: {
          left: 30,
          top: 14,
          width: 40,
          height: 6,
          zIndex: 10,
          color: '#60a5fa',
          fontSize: 1.1,
          fontWeight: 'semibold',
          textAlign: 'center',
          letterSpacing: '0.15em',
          textTransform: 'uppercase',
          backgroundColor: 'rgba(59, 130, 246, 0.15)',
          borderColor: 'rgba(96, 165, 250, 0.3)',
          borderWidth: 1,
          borderRadius: 999,
          padding: 8,
        },
        content: {
          text: '✦ GLOBAL TECH SUMMIT 2026 • MAIN AUDITORIUM',
        },
      },
      {
        id: 'el-welcome-title',
        type: 'text',
        name: 'Main Title',
        style: {
          left: 10,
          top: 24,
          width: 80,
          height: 18,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 3.8,
          fontWeight: 'black',
          textAlign: 'center',
          lineHeight: 1.1,
          textShadow: '0 4px 24px rgba(0,0,0,0.8)',
        },
        content: {
          text: 'WELCOME TO THE FUTURE OF AUTONOMOUS SYSTEMS',
        },
      },
      {
        id: 'el-welcome-sub',
        type: 'text',
        name: 'Subtitle',
        style: {
          left: 18,
          top: 45,
          width: 64,
          height: 10,
          zIndex: 10,
          color: '#94a3b8',
          fontSize: 1.5,
          fontWeight: 'medium',
          textAlign: 'center',
          lineHeight: 1.4,
        },
        content: {
          text: 'Keynote Session Begins at 10:00 AM • Please Take Your Seats',
        },
      },
      {
        id: 'el-welcome-qr-card',
        type: 'shape',
        name: 'QR Container Card',
        style: {
          left: 37,
          top: 58,
          width: 26,
          height: 28,
          zIndex: 8,
          backgroundColor: 'rgba(15, 23, 42, 0.75)',
          borderColor: 'rgba(148, 163, 184, 0.2)',
          borderWidth: 1,
          borderRadius: 16,
          backdropBlur: 16,
          boxShadow: '0 20px 40px rgba(0, 0, 0, 0.6)',
        },
        content: {},
      },
      {
        id: 'el-welcome-qr',
        type: 'qrcode',
        name: 'Event Guide QR Code',
        style: {
          left: 42.5,
          top: 61,
          width: 15,
          height: 16,
          zIndex: 12,
        },
        content: {
          qrUrl: 'https://smartscreen.live/schedule',
          qrLabel: 'Scan for Live Schedule & Q&A',
        },
      },
      {
        id: 'el-welcome-footer',
        type: 'text',
        name: 'Wifi & Info Footer',
        style: {
          left: 15,
          top: 90,
          width: 70,
          height: 6,
          zIndex: 10,
          color: '#64748b',
          fontSize: 1.0,
          fontWeight: 'medium',
          textAlign: 'center',
          letterSpacing: '0.05em',
        },
        content: {
          text: 'Guest Wi-Fi: TechSummit-Guest  •  Password: innovate2026',
        },
      },
    ],
  },
  {
    id: 'scene-rules',
    name: 'Competition Rules & Guidelines',
    type: 'rules',
    description: 'Live tournament rules and fair play criteria',
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #0b132b 0%, #1c2541 50%, #0b132b 100%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 3000000,
    updatedAt: Date.now() - 3000000,
    elements: [
      {
        id: 'el-rules-heading',
        type: 'text',
        name: 'Rules Heading',
        style: {
          left: 10,
          top: 8,
          width: 80,
          height: 12,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 3.0,
          fontWeight: 'black',
          textAlign: 'center',
          letterSpacing: '0.05em',
        },
        content: {
          text: 'OFFICIAL HACKATHON REGULATIONS',
        },
      },
      {
        id: 'el-rules-sub',
        type: 'text',
        name: 'Rules Subtitle',
        style: {
          left: 15,
          top: 20,
          width: 70,
          height: 6,
          zIndex: 10,
          color: '#38bdf8',
          fontSize: 1.2,
          fontWeight: 'semibold',
          textAlign: 'center',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
        },
        content: {
          text: 'Phase 1 • Code Freeze at 12:00 PM • Adherence is Strictly Enforced',
        },
      },
      {
        id: 'el-rules-cards',
        type: 'rule_cards',
        name: 'Rule Cards Grid',
        style: {
          left: 8,
          top: 28,
          width: 84,
          height: 58,
          zIndex: 10,
        },
        content: {
          ruleCardsData: [
            {
              number: 1,
              title: 'Original Source Code Only',
              description: 'All submitted repositories must have initial commit after the opening bell. Pre-built codebases result in immediate disqualification.',
              tag: 'Integrity',
            },
            {
              number: 2,
              title: 'Mandatory Public Commits',
              description: 'Teams must push commits to the designated GitHub organization every 60 minutes for timestamp verification.',
              tag: 'Version Control',
            },
            {
              number: 3,
              title: 'Authorized API Keys Only',
              description: 'Teams are provided unified sponsor API keys. Third-party commercial APIs require approval from lead judges.',
              tag: 'Fair Play',
            },
            {
              number: 4,
              title: 'Live 3-Minute Presentation',
              description: 'Final scoring consists of a live demonstration. Slides are strictly limited to 2 slides maximum.',
              tag: 'Demo Standard',
            },
          ],
        },
      },
      {
        id: 'el-rules-footer',
        type: 'text',
        name: 'Questions Info',
        style: {
          left: 10,
          top: 90,
          width: 80,
          height: 6,
          zIndex: 10,
          color: '#94a3b8',
          fontSize: 1.0,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'Questions? Find any Mentor with a Green Badge or join #help-desk on Slack',
        },
      },
    ],
  },
  {
    id: 'scene-timer',
    name: 'Live Countdown Arena',
    type: 'timer',
    description: 'High visibility synchronized timer display for physical screens',
    background: {
      type: 'gradient',
      value: 'radial-gradient(circle at center, #172554 0%, #030712 75%)',
    },
    transition: 'zoom',
    createdAt: Date.now() - 2500000,
    updatedAt: Date.now() - 2500000,
    elements: [
      {
        id: 'el-timer-banner',
        type: 'text',
        name: 'Round Badge',
        style: {
          left: 32,
          top: 10,
          width: 36,
          height: 6,
          zIndex: 10,
          color: '#fbbf24',
          fontSize: 1.2,
          fontWeight: 'bold',
          textAlign: 'center',
          letterSpacing: '0.2em',
          textTransform: 'uppercase',
          backgroundColor: 'rgba(251, 191, 36, 0.12)',
          borderColor: 'rgba(251, 191, 36, 0.3)',
          borderWidth: 1,
          borderRadius: 999,
          padding: 8,
        },
        content: {
          text: '⚡ ACTIVE SESSION: ROUND 1 CHALLENGE',
        },
      },
      {
        id: 'el-timer-clock',
        type: 'timer',
        name: 'Big Central Timer',
        style: {
          left: 15,
          top: 20,
          width: 70,
          height: 44,
          zIndex: 12,
          color: '#ffffff',
          fontSize: 7.5,
          fontWeight: 'black',
          textAlign: 'center',
          letterSpacing: '0.04em',
        },
        content: {
          timerLabel: 'TIME REMAINING',
          timerFormat: 'MM:SS',
        },
      },
      {
        id: 'el-timer-sub',
        type: 'text',
        name: 'Round Instructions',
        style: {
          left: 20,
          top: 68,
          width: 60,
          height: 10,
          zIndex: 10,
          color: '#94a3b8',
          fontSize: 1.5,
          fontWeight: 'medium',
          textAlign: 'center',
          lineHeight: 1.3,
        },
        content: {
          text: 'Push Final Commits before timer expires • System locks automatically at 00:00',
        },
      },
      {
        id: 'el-timer-bar',
        type: 'divider',
        name: 'Accent Divider',
        style: {
          left: 35,
          top: 80,
          width: 30,
          height: 1,
          zIndex: 10,
          backgroundColor: 'rgba(251, 191, 36, 0.4)',
        },
        content: {},
      },
      {
        id: 'el-timer-next',
        type: 'text',
        name: 'Next Phase Notice',
        style: {
          left: 25,
          top: 85,
          width: 50,
          height: 6,
          zIndex: 10,
          color: '#64748b',
          fontSize: 1.1,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'UP NEXT: Lunch Break & Mentor Checkpoint at 12:30 PM',
        },
      },
    ],
  },
  {
    id: 'scene-announcement',
    name: 'Important Announcement',
    type: 'announcement',
    description: 'High priority event broadcast announcement',
    background: {
      type: 'gradient',
      value: 'linear-gradient(180deg, #18181b 0%, #09090b 100%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 2000000,
    updatedAt: Date.now() - 2000000,
    elements: [
      {
        id: 'el-ann-card',
        type: 'shape',
        name: 'Card Background',
        style: {
          left: 12,
          top: 14,
          width: 76,
          height: 72,
          zIndex: 5,
          backgroundColor: 'rgba(24, 24, 27, 0.85)',
          borderColor: 'rgba(59, 130, 246, 0.4)',
          borderWidth: 2,
          borderRadius: 24,
          boxShadow: '0 25px 60px rgba(0,0,0,0.7)',
          backdropBlur: 20,
        },
        content: {},
      },
      {
        id: 'el-ann-tag',
        type: 'text',
        name: 'Notice Tag',
        style: {
          left: 36,
          top: 22,
          width: 28,
          height: 6,
          zIndex: 10,
          color: '#38bdf8',
          fontSize: 1.2,
          fontWeight: 'bold',
          textAlign: 'center',
          letterSpacing: '0.15em',
          textTransform: 'uppercase',
          backgroundColor: 'rgba(56, 189, 248, 0.15)',
          borderRadius: 999,
          padding: 6,
        },
        content: {
          text: '📢 EVENT ANNOUNCEMENT',
        },
      },
      {
        id: 'el-ann-headline',
        type: 'text',
        name: 'Headline',
        style: {
          left: 16,
          top: 32,
          width: 68,
          height: 18,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 3.2,
          fontWeight: 'black',
          textAlign: 'center',
          lineHeight: 1.15,
        },
        content: {
          text: 'KEYNOTE WORKSHOP MOVED TO HALL B',
        },
      },
      {
        id: 'el-ann-body',
        type: 'text',
        name: 'Message Body',
        style: {
          left: 20,
          top: 52,
          width: 60,
          height: 20,
          zIndex: 10,
          color: '#cbd5e1',
          fontSize: 1.6,
          fontWeight: 'normal',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        content: {
          text: 'Due to overwhelming attendance, Dr. Aris Thorne\'s session on Generative Systems Architecture will now take place in Hall B (2nd Floor). Doors open in 15 minutes.',
        },
      },
      {
        id: 'el-ann-action',
        type: 'text',
        name: 'Action Reminder',
        style: {
          left: 20,
          top: 74,
          width: 60,
          height: 6,
          zIndex: 10,
          color: '#f59e0b',
          fontSize: 1.1,
          fontWeight: 'semibold',
          textAlign: 'center',
        },
        content: {
          text: '→ Please show your digital summit pass at the Hall B entrance',
        },
      },
    ],
  },
  {
    id: 'scene-break',
    name: 'Intermission & Networking',
    type: 'break',
    description: 'Event intermission, coffee break, and networking display',
    background: {
      type: 'gradient',
      value: 'radial-gradient(ellipse at bottom, #1e293b 0%, #0f172a 50%, #020617 100%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 1500000,
    updatedAt: Date.now() - 1500000,
    elements: [
      {
        id: 'el-break-title',
        type: 'text',
        name: 'Break Title',
        style: {
          left: 15,
          top: 18,
          width: 70,
          height: 14,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 3.6,
          fontWeight: 'black',
          textAlign: 'center',
          letterSpacing: '0.04em',
        },
        content: {
          text: '☕ INTERMISSION & NETWORKING',
        },
      },
      {
        id: 'el-break-sub',
        type: 'text',
        name: 'Break Subtitle',
        style: {
          left: 20,
          top: 34,
          width: 60,
          height: 8,
          zIndex: 10,
          color: '#94a3b8',
          fontSize: 1.5,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'Refreshments are served in the Grand Atrium & Exhibit Lounge',
        },
      },
      {
        id: 'el-break-time-card',
        type: 'shape',
        name: 'Resume Time Card',
        style: {
          left: 32,
          top: 46,
          width: 36,
          height: 24,
          zIndex: 8,
          backgroundColor: 'rgba(30, 41, 59, 0.7)',
          borderColor: 'rgba(99, 102, 241, 0.3)',
          borderWidth: 1,
          borderRadius: 20,
          boxShadow: '0 20px 45px rgba(0, 0, 0, 0.5)',
        },
        content: {},
      },
      {
        id: 'el-break-resume-label',
        type: 'text',
        name: 'Resume Label',
        style: {
          left: 34,
          top: 50,
          width: 32,
          height: 5,
          zIndex: 10,
          color: '#818cf8',
          fontSize: 1.1,
          fontWeight: 'bold',
          textAlign: 'center',
          letterSpacing: '0.15em',
          textTransform: 'uppercase',
        },
        content: {
          text: 'PROGRAM RESUMES AT',
        },
      },
      {
        id: 'el-break-resume-time',
        type: 'text',
        name: 'Resume Time Value',
        style: {
          left: 34,
          top: 56,
          width: 32,
          height: 12,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 3.4,
          fontWeight: 'black',
          textAlign: 'center',
        },
        content: {
          text: '01:30 PM',
        },
      },
      {
        id: 'el-break-footer',
        type: 'text',
        name: 'Next Topic',
        style: {
          left: 15,
          top: 76,
          width: 70,
          height: 6,
          zIndex: 10,
          color: '#64748b',
          fontSize: 1.2,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'Session 2: "Frontiers in Multimodal AI" with Panel of Chief Scientists',
        },
      },
    ],
  },
  {
    id: 'scene-results',
    name: 'Leaderboard & Results',
    type: 'results',
    description: 'Live tournament ranking and competition results table',
    background: {
      type: 'gradient',
      value: 'linear-gradient(135deg, #090d16 0%, #111827 50%, #030712 100%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 1000000,
    elements: [
      {
        id: 'el-res-title',
        type: 'text',
        name: 'Results Title',
        style: {
          left: 10,
          top: 6,
          width: 80,
          height: 10,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 2.8,
          fontWeight: 'black',
          textAlign: 'center',
          letterSpacing: '0.06em',
        },
        content: {
          text: '🏆 HACKATHON LIVE LEADERBOARD',
        },
      },
      {
        id: 'el-res-subtitle',
        type: 'text',
        name: 'Subtitle',
        style: {
          left: 15,
          top: 17,
          width: 70,
          height: 5,
          zIndex: 10,
          color: '#10b981',
          fontSize: 1.1,
          fontWeight: 'bold',
          textAlign: 'center',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
        },
        content: {
          text: 'OFFICIAL REALTIME STANDINGS • AUDITED BY JUDGES PANEL',
        },
      },
      {
        id: 'el-res-table',
        type: 'leaderboard',
        name: 'Leaderboard Component',
        style: {
          left: 10,
          top: 24,
          width: 80,
          height: 64,
          zIndex: 10,
        },
        content: {
          leaderboardData: [
            { rank: 1, name: 'Team NeuralForge', score: '98.5 pts', badge: '🥇 1st Place' },
            { rank: 2, name: 'Quantum Leap Labs', score: '96.2 pts', badge: '🥈 2nd Place' },
            { rank: 3, name: 'HyperScale AI', score: '94.0 pts', badge: '🥉 3rd Place' },
            { rank: 4, name: 'Synthetix Cloud', score: '91.8 pts', badge: 'Top 5 Finalist' },
            { rank: 5, name: 'Apex Robotics', score: '89.4 pts', badge: 'Top 5 Finalist' },
          ],
        },
      },
      {
        id: 'el-res-footer',
        type: 'text',
        name: 'Footer',
        style: {
          left: 10,
          top: 91,
          width: 80,
          height: 5,
          zIndex: 10,
          color: '#64748b',
          fontSize: 1.0,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'Award Ceremony at 04:30 PM on Main Stage • All Finalists Must Be Present',
        },
      },
    ],
  },
  {
    id: 'scene-thank-you',
    name: 'Thank You & Closing',
    type: 'thank_you',
    description: 'End-of-event closing and feedback screen',
    background: {
      type: 'gradient',
      value: 'radial-gradient(circle at center, #1e1b4b 0%, #030712 90%)',
    },
    transition: 'fade',
    createdAt: Date.now() - 500000,
    updatedAt: Date.now() - 500000,
    elements: [
      {
        id: 'el-ty-title',
        type: 'text',
        name: 'Thank You Title',
        style: {
          left: 10,
          top: 16,
          width: 80,
          height: 14,
          zIndex: 10,
          color: '#ffffff',
          fontSize: 4.2,
          fontWeight: 'black',
          textAlign: 'center',
        },
        content: {
          text: 'THANK YOU FOR ATTENDING',
        },
      },
      {
        id: 'el-ty-sub',
        type: 'text',
        name: 'Subtitle',
        style: {
          left: 15,
          top: 32,
          width: 70,
          height: 8,
          zIndex: 10,
          color: '#a5b4fc',
          fontSize: 1.6,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'We hope to see you next year at Global Tech Summit 2027!',
        },
      },
      {
        id: 'el-ty-qr',
        type: 'qrcode',
        name: 'Feedback QR',
        style: {
          left: 42.5,
          top: 45,
          width: 15,
          height: 18,
          zIndex: 10,
        },
        content: {
          qrUrl: 'https://smartscreen.live/feedback',
          qrLabel: 'Scan to Share Feedback & Claim Certificate',
        },
      },
      {
        id: 'el-ty-contact',
        type: 'text',
        name: 'Contact & Socials',
        style: {
          left: 15,
          top: 80,
          width: 70,
          height: 6,
          zIndex: 10,
          color: '#64748b',
          fontSize: 1.2,
          fontWeight: 'medium',
          textAlign: 'center',
        },
        content: {
          text: 'Keep in touch: @GlobalTechSummit  •  contact@techsummit.io',
        },
      },
    ],
  },
];

export const defaultAnnouncements: AnnouncementItem[] = [
  {
    id: 'ann-1',
    title: 'Round 1 Code Freeze in 10 Minutes',
    content: 'All participants must commit and push all code before 12:00 PM.',
    priority: 'high',
    status: 'queued',
    order: 1,
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'ann-2',
    title: 'Lunch Served in Main Atrium',
    content: 'Catered lunch is available from 12:30 PM to 01:30 PM in Hall A.',
    priority: 'medium',
    status: 'queued',
    order: 2,
    createdAt: Date.now() - 3000000,
  },
  {
    id: 'ann-3',
    title: 'Dr. Aris Thorne Workshop Relocation',
    content: 'Workshop has relocated to Hall B on the 2nd Floor.',
    priority: 'high',
    status: 'active',
    order: 3,
    createdAt: Date.now() - 2000000,
  },
  {
    id: 'ann-4',
    title: 'Lost and Found: Silver Laptop Charger',
    content: 'A MacBook charger was turned into the Help Desk in the lobby.',
    priority: 'low',
    status: 'queued',
    order: 4,
    createdAt: Date.now() - 1000000,
  },
];

export const defaultSchedule: ScheduleItem[] = [
  {
    id: 'sch-1',
    sceneId: 'scene-welcome',
    sceneName: 'Main Welcome Display',
    scheduledTime: '09:00',
    title: 'Doors Open & Attendee Registration',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-2',
    sceneId: 'scene-rules',
    sceneName: 'Competition Rules & Guidelines',
    scheduledTime: '09:30',
    title: 'Opening Remarks & Competition Rules Briefing',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-3',
    sceneId: 'scene-timer',
    sceneName: 'Live Countdown Arena',
    scheduledTime: '10:00',
    title: 'Round 1 Kickoff & Hackathon Timer',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-4',
    sceneId: 'scene-break',
    sceneName: 'Intermission & Networking',
    scheduledTime: '12:30',
    title: 'Lunch Break & Partner Networking',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-5',
    sceneId: 'scene-sponsor',
    sceneName: 'Sponsor & Partner Showcase',
    scheduledTime: '13:30',
    title: 'Sponsor Keynote & Technology Demos',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-6',
    sceneId: 'scene-results',
    sceneName: 'Leaderboard & Results',
    scheduledTime: '16:00',
    title: 'Live Finals & Final Leaderboard Reveal',
    enabled: true,
    autoTrigger: false,
  },
  {
    id: 'sch-7',
    sceneId: 'scene-thank-you',
    sceneName: 'Thank You & Closing',
    scheduledTime: '17:00',
    title: 'Award Ceremony & Closing Reception',
    enabled: true,
    autoTrigger: false,
  },
];

export const defaultAssets: AssetItem[] = [
  {
    id: 'asset-bg-nebula',
    name: 'Cosmic Gradient High-Res',
    type: 'background',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1920&auto=format&fit=crop&q=80',
    size: 1420000,
    uploadedAt: Date.now() - 86400000,
  },
  {
    id: 'asset-bg-dark-mesh',
    name: 'Cyber Grid Dark Backdrop',
    type: 'background',
    url: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1920&auto=format&fit=crop&q=80',
    size: 2150000,
    uploadedAt: Date.now() - 72000000,
  },
  {
    id: 'asset-bg-stage',
    name: 'Auditorium Stage Lights',
    type: 'background',
    url: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1920&auto=format&fit=crop&q=80',
    size: 1890000,
    uploadedAt: Date.now() - 50000000,
  },
  {
    id: 'asset-logo-summit',
    name: 'TechSummit Vector Emblem',
    type: 'logo',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
    size: 120000,
    uploadedAt: Date.now() - 40000000,
  },
  {
    id: 'asset-img-trophy',
    name: 'Golden Championship Cup',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1578269174936-2709b6aeb913?w=800&auto=format&fit=crop&q=80',
    size: 890000,
    uploadedAt: Date.now() - 20000000,
  },
];

export const defaultInitialEventState: EventState = {
  id: 'current',
  activeSceneId: 'scene-welcome',
  overrideMode: 'none',
  emergency: {
    active: false,
    title: 'SAFETY NOTICE',
    message: 'Please follow venue staff instructions.',
    severity: 'critical',
    audioAlert: true,
    timestamp: Date.now(),
  },
  timer: defaultTimerState,
  bannerAnnouncement: null,
  brandKit: defaultBrandKit,
  version: 1,
  updatedAt: Date.now(),
};
